/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 portfolio_animated.glb --transform 
Files: portfolio_animated.glb [2.64MB] > C:\Users\erski\OneDrive\Documents\GitHub\bennettdev-portfolio\public\portfolio_animated-transformed.glb [1.02MB] (61%)
*/

import React, { act, Suspense, useEffect } from 'react'
import { useGLTF, useAnimations, Bounds } from '@react-three/drei'
import * as THREE from 'three';
import VideoMaterial from "./VideoMaterial";

import EFTSVideo from 'EFTSGameplay.mp4';
import SelectToZoom from './SelectToZoom';
import { useModalStore } from '../stores/modalStore';
import AboutMe from '../../components/AboutMe/AboutMe';
import Projects from '../../components/Projects/Projects';
import Games from '../../components/Games/Games';
import { useZoomStore } from '../stores/zoomStore';
import CTF from '../../components/CTF/CTF';

export default function Model({props, camera, zoomToView}) {
  //console.log(zoomToView);
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF('portfolio_animated-transformed.glb')
  const { actions } = useAnimations(animations, group)

  const meshRef = React.useRef();

  const { openModal } = useModalStore();
  const {zoom,setZoom,focus,setFocus} = useZoomStore();

  const handleClickModal = (elementName) => {
    console.log("Click handled " + elementName);
    if(zoom) return;
    if(elementName === "AboutMe") {
      openModal("About Me", <AboutMe/>, elementName);
    }
    else if (elementName === "Projects") {
      openModal("Projects", <Projects/>, elementName);
    } 
    else if (elementName === "Games") {
      openModal("Games", <Games/>, elementName);
    } else if (elementName === "CTF") {
      openModal("CTF", <CTF/>, elementName);
    }
  }

  const zoomToModalObject = (objectPos) => {
    if(zoom) return;
    setZoom(true);
    setFocus(objectPos);
  }

  const zoomToObject = (objectPos) => {

    if(objectPos === focus ) {
      setZoom(!zoom);
    } else {
      setZoom(true);
    }
   
    setFocus(objectPos);
  }

  const zoomToRoomView = () => {
    setZoom(false);
  }

  //console.log(nodes.Screen.geometry);

    useEffect(()=> {
      if(actions) {  
        Object.values(actions).forEach((action) => {
          //console.log("playing animation" + action);
          //console.log(action.getClip().name);

          if(action.getClip().name == "FanAction" || action.getClip().name == "Part") {
            //console.log("Fan Action identified");
            action.play();
          }
          //action.play();
        })
          
        
      }
    }, [actions]);


    const PauseAnimation = ((e) => {
      //actions[curAnimaion].paused = true;

        //Object.values(actions).forEach((action) => {
        //  action.paused = true;
       // })
          
    })

    useEffect(() => {
      if (meshRef.current) {
        //console.log(meshRef.current); // Logs the actual DOM element
      }
    }, [meshRef]);

    const PlayAnimation = ({e}) => 
    {
      //console.log(e.eventObject.name);
      const meshName = e.eventObject.name;
      const actionEnding = "Action";
      let otherMeshName = e.eventObject.name;

      if(meshName === "ArcadeCabinet" || meshName === "GlassCabinet") {
        otherMeshName = (meshName === "ArcadeCabinet") ? "GlassCabinet": "ArcadeCabinet";
        console.log("Arcade Cabinet detected");
        if(!actions[GetAnimationName(otherMeshName)].isRunning()) {
          actions[GetAnimationName(otherMeshName)].stop();
          //actions[GetAnimationName(meshName)].paused = false;
          actions[GetAnimationName(otherMeshName)].loop = THREE.LoopOnce;
          actions[GetAnimationName(otherMeshName)].play();
        }
      }

      //Play New one
      if(meshName) {
        const animationName = GetAnimationName(meshName);
        console.log(meshName);
        
        if(!actions[GetAnimationName(meshName)].isRunning()) {
          actions[GetAnimationName(meshName)].stop();
          //actions[GetAnimationName(meshName)].paused = false;
          actions[GetAnimationName(meshName)].loop = THREE.LoopOnce;
          actions[GetAnimationName(meshName)].play();
        }

      }
    }

    const GetAnimationName = (meshName) => {
      let newMeshName = meshName;
      const actionEnding = "Action";

      if(meshName) {
        //console.log(meshName.charAt(meshName.length - 3));
        if(meshName == "Kayboard") {
          newMeshName = "KayboardAction.001";
          //console.log("Playing Animation: " + newMeshName);
        }
        else if(meshName.charAt(meshName.length - 3) == '0') {
          newMeshName = meshName.slice(0, meshName.length - 3) + '.' + meshName.slice(meshName.length - 3) + actionEnding;
          //console.log("Playing Animation: " + newMeshName);
        }
        else {        
          newMeshName = meshName + actionEnding;
        }

      }
      return newMeshName;
    }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
      <mesh name="Room" geometry={nodes.Room.geometry} material={materials.PaletteMaterial001} position={[3.105, 24.532, 0]} />
      <mesh name="Description" geometry={nodes.Description.geometry} material={materials.PaletteMaterial001} position={[-3.992, 28.295, -31.044]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Name" geometry={nodes.Name.geometry} material={materials.PaletteMaterial001} position={[-3.993, 30.041, -31.198]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Table" geometry={nodes.Table.geometry} material={materials.PaletteMaterial001} position={[-2.999, 2.321, 0]} />
      <mesh name="TableEdge" geometry={nodes.TableEdge.geometry} material={materials.PaletteMaterial001} position={[-3.043, 2.291, 0.003]} />
      <mesh name="TableEdge001" geometry={nodes.TableEdge001.geometry} material={materials.PaletteMaterial001} position={[-2.859, 1.896, 0.014]} rotation={[0, Math.PI / 2, 0]} />
      <mesh name="Leg" geometry={nodes.Leg.geometry} material={materials.PaletteMaterial001} position={[4.952, 0, 0]} />
      <mesh name="Matt" geometry={nodes.Matt.geometry} material={materials.PaletteMaterial001} position={[-2.999, 3.669, 2.86]}/>

      <mesh name="Monitor" geometry={nodes.Monitor.geometry} material={materials.PaletteMaterial001} position={[-3.273, 6.915, -6.265]} 
      onPointerOver={(e)=> PlayAnimation({e})} onClick={(e) => {zoomToObject(e.object.position); handleClickModal("")}} >
        <mesh position={[0, 2, 4.3]}>
          {<VideoMaterial src={EFTSVideo} />}
          <planeGeometry args={[14, 6, 2, 2]} />
        </mesh>
      </mesh>

      <mesh name="Mouse" geometry={nodes.Mouse.geometry} material={materials.PaletteMaterial001} position={[1.089, 3.658, 1.75]}  
      onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} onClick={(e) => zoomToObject(e.object.position)}/>

      <mesh name="Pringles" geometry={nodes.Pringles.geometry} material={materials.PaletteMaterial001} position={[3.48, 5.576, 1.615]}  
      onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} onClick={(e) => zoomToObject(e.object.position)}/>
      
      <group name="Painting" position={[-20.323, 20.879, -30.836]}  
      onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} 
      onClick={(e) => {zoomToModalObject((e.object.parent) ? e.object.parent.position: e.object.position); handleClickModal("AboutMe")}}>
        <mesh name="Cube190" geometry={nodes.Cube190.geometry} material={materials.PaletteMaterial002} />
        <mesh name="Cube190_1" geometry={nodes.Cube190_1.geometry} material={materials['Material.003']} />
      </group>

      <group name="Painting001" position={[-3.49, 17.224, -30.32]}  
      onPointerOver={(e)=> PlayAnimation({e})} 
      onClick={(e) => {zoomToModalObject((e.object.parent) ? e.object.parent.position: e.object.position); handleClickModal("Projects")}}>
        <mesh name="Cube192" geometry={nodes.Cube192.geometry} material={materials.PaletteMaterial002} />
        <mesh name="Cube192_1" geometry={nodes.Cube192_1.geometry} material={materials['Material.005']} />
      </group>

      <group name="Painting002" position={[12.54, 21.04, -30.901]} 
      onPointerOver={(e)=> PlayAnimation({e})} 
      onClick={(e) => {zoomToModalObject((e.object.parent) ? e.object.parent.position: e.object.position); handleClickModal("Games")}}>
        <mesh name="Cube193" geometry={nodes.Cube193.geometry} material={materials.PaletteMaterial002} />
        <mesh name="Cube193_1" geometry={nodes.Cube193_1.geometry} material={materials['Material.006']} />
      </group>

      <mesh name="Amongus" geometry={nodes.Amongus.geometry} material={materials.PaletteMaterial001} position={[-11.232, 4.278, -1.472]}  
      onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} 
      onClick={(e) => zoomToObject(e.object.position)}/>
      
      <mesh name="ArcadeCabinet" geometry={nodes.ArcadeCabinet.geometry} material={materials.PaletteMaterial001} position={[27.023, 6.033, -25.735]} 
      onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} onClick={(e) => {zoomToModalObject(e.object.position); handleClickModal("CTF")}}/>
      
      <mesh name="Claw" geometry={nodes.Claw.geometry} material={materials.PaletteMaterial001} position={[27.594, 11.611, -25.697]} />
      
      <mesh name="GlassCabinet" geometry={nodes.GlassCabinet.geometry} material={materials.PaletteMaterial003} position={[27.233, 10.395, -26.052]} 
      onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} onClick={(e) => {zoomToModalObject(e.object.position); handleClickModal("CTF")}}/>

      <mesh name="Kayboard" geometry={nodes.Kayboard.geometry} material={materials.PaletteMaterial001} position={[-6.28, 4.103, 1.738]}  onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} onClick={(e) => zoomToObject(new THREE.Vector3(-6.28, 4.103, 1.738))}>
        <mesh name="Keys" geometry={nodes.Keys.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys002" geometry={nodes.Keys002.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys003" geometry={nodes.Keys003.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys004" geometry={nodes.Keys004.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys005" geometry={nodes.Keys005.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys007" geometry={nodes.Keys007.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys008" geometry={nodes.Keys008.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys009" geometry={nodes.Keys009.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys010" geometry={nodes.Keys010.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys012" geometry={nodes.Keys012.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys013" geometry={nodes.Keys013.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys014" geometry={nodes.Keys014.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys015" geometry={nodes.Keys015.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys017" geometry={nodes.Keys017.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys018" geometry={nodes.Keys018.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys019" geometry={nodes.Keys019.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys020" geometry={nodes.Keys020.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys022" geometry={nodes.Keys022.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys023" geometry={nodes.Keys023.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys024" geometry={nodes.Keys024.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys025" geometry={nodes.Keys025.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys026" geometry={nodes.Keys026.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys027" geometry={nodes.Keys027.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys028" geometry={nodes.Keys028.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys029" geometry={nodes.Keys029.geometry} material={materials.PaletteMaterial001} position={[-4.567, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys030" geometry={nodes.Keys030.geometry} material={materials.PaletteMaterial001} position={[-4.581, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys031" geometry={nodes.Keys031.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys032" geometry={nodes.Keys032.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys033" geometry={nodes.Keys033.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys034" geometry={nodes.Keys034.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys035" geometry={nodes.Keys035.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys036" geometry={nodes.Keys036.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys037" geometry={nodes.Keys037.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys038" geometry={nodes.Keys038.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys039" geometry={nodes.Keys039.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys040" geometry={nodes.Keys040.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys041" geometry={nodes.Keys041.geometry} material={materials.PaletteMaterial001} position={[-4.623, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys042" geometry={nodes.Keys042.geometry} material={materials.PaletteMaterial001} position={[-4.615, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys043" geometry={nodes.Keys043.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys045" geometry={nodes.Keys045.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys046" geometry={nodes.Keys046.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys047" geometry={nodes.Keys047.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys048" geometry={nodes.Keys048.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys050" geometry={nodes.Keys050.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys051" geometry={nodes.Keys051.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys052" geometry={nodes.Keys052.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys053" geometry={nodes.Keys053.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys054" geometry={nodes.Keys054.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys055" geometry={nodes.Keys055.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys056" geometry={nodes.Keys056.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys057" geometry={nodes.Keys057.geometry} material={materials.PaletteMaterial001} position={[-4.569, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys058" geometry={nodes.Keys058.geometry} material={materials.PaletteMaterial001} position={[-4.57, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys059" geometry={nodes.Keys059.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys060" geometry={nodes.Keys060.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys061" geometry={nodes.Keys061.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys062" geometry={nodes.Keys062.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys063" geometry={nodes.Keys063.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys064" geometry={nodes.Keys064.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys065" geometry={nodes.Keys065.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys066" geometry={nodes.Keys066.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys067" geometry={nodes.Keys067.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys068" geometry={nodes.Keys068.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys069" geometry={nodes.Keys069.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys070" geometry={nodes.Keys070.geometry} material={materials.PaletteMaterial001} position={[-4.607, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys071" geometry={nodes.Keys071.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys073" geometry={nodes.Keys073.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys074" geometry={nodes.Keys074.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys075" geometry={nodes.Keys075.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys076" geometry={nodes.Keys076.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.775]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys078" geometry={nodes.Keys078.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys079" geometry={nodes.Keys079.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys080" geometry={nodes.Keys080.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys081" geometry={nodes.Keys081.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys082" geometry={nodes.Keys082.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys084" geometry={nodes.Keys084.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys086" geometry={nodes.Keys086.geometry} material={materials.PaletteMaterial001} position={[-4.616, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys087" geometry={nodes.Keys087.geometry} material={materials.PaletteMaterial001} position={[-4.579, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys088" geometry={nodes.Keys088.geometry} material={materials.PaletteMaterial001} position={[-4.59, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys089" geometry={nodes.Keys089.geometry} material={materials.PaletteMaterial001} position={[-4.61, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys090" geometry={nodes.Keys090.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys091" geometry={nodes.Keys091.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys092" geometry={nodes.Keys092.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys093" geometry={nodes.Keys093.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys094" geometry={nodes.Keys094.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys095" geometry={nodes.Keys095.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys096" geometry={nodes.Keys096.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys097" geometry={nodes.Keys097.geometry} material={materials.PaletteMaterial001} position={[-4.626, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys098" geometry={nodes.Keys098.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys106" geometry={nodes.Keys106.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys107" geometry={nodes.Keys107.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys108" geometry={nodes.Keys108.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys109" geometry={nodes.Keys109.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys110" geometry={nodes.Keys110.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys111" geometry={nodes.Keys111.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys112" geometry={nodes.Keys112.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys114" geometry={nodes.Keys114.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys115" geometry={nodes.Keys115.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys116" geometry={nodes.Keys116.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys117" geometry={nodes.Keys117.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys118" geometry={nodes.Keys118.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys119" geometry={nodes.Keys119.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys120" geometry={nodes.Keys120.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys121" geometry={nodes.Keys121.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys122" geometry={nodes.Keys122.geometry} material={materials.PaletteMaterial001} position={[-4.615, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys123" geometry={nodes.Keys123.geometry} material={materials.PaletteMaterial001} position={[-4.616, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys124" geometry={nodes.Keys124.geometry} material={materials.PaletteMaterial001} position={[-4.641, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys125" geometry={nodes.Keys125.geometry} material={materials.PaletteMaterial001} position={[-4.647, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys126" geometry={nodes.Keys126.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys130" geometry={nodes.Keys130.geometry} material={materials.PaletteMaterial001} position={[-4.368, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys134" geometry={nodes.Keys134.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys135" geometry={nodes.Keys135.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys136" geometry={nodes.Keys136.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys137" geometry={nodes.Keys137.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys138" geometry={nodes.Keys138.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys140" geometry={nodes.Keys140.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys141" geometry={nodes.Keys141.geometry} material={materials.PaletteMaterial001} position={[-4.392, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys142" geometry={nodes.Keys142.geometry} material={materials.PaletteMaterial001} position={[-4.272, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys144" geometry={nodes.Keys144.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys151" geometry={nodes.Keys151.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys153" geometry={nodes.Keys153.geometry} material={materials.PaletteMaterial001} position={[-4.891, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys154" geometry={nodes.Keys154.geometry} material={materials.PaletteMaterial001} position={[-4.816, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys155" geometry={nodes.Keys155.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys157" geometry={nodes.Keys157.geometry} material={materials.PaletteMaterial001} position={[-4.368, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys158" geometry={nodes.Keys158.geometry} material={materials.PaletteMaterial001} position={[-4.368, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys159" geometry={nodes.Keys159.geometry} material={materials.PaletteMaterial001} position={[-4.368, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys162" geometry={nodes.Keys162.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys165" geometry={nodes.Keys165.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys166" geometry={nodes.Keys166.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
        <mesh name="Keys167" geometry={nodes.Keys167.geometry} material={materials.PaletteMaterial001} position={[-4.592, -0.18, -1.84]} rotation={[0.085, 0, 0]} />
      </mesh>
      <mesh name="Pot" geometry={nodes.Pot.geometry} material={materials.PaletteMaterial001} position={[5.325, 3.965, -0.123]} rotation={[-0.087, 0.091, -0.014]}  onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} onClick={(e) => zoomToObject(new THREE.Vector3(5.325, 3.965, -0.123))}> 
        <mesh name="Cactus" geometry={nodes.Cactus.geometry} material={materials.PaletteMaterial001} position={[0.016, 0.994, 0.214]} rotation={[-0.118, 0.042, -0.013]} />
        <mesh name="Flower" geometry={nodes.Flower.geometry} material={materials.PaletteMaterial001} position={[0.012, 2.459, 0.387]} rotation={[0.089, -0.089, 0.022]} />
        <mesh name="Petal" geometry={nodes.Petal.geometry} material={materials.PaletteMaterial001} position={[0.28, 2.289, 0.632]} rotation={[0.089, -0.089, 0.022]} />
        <mesh name="Petal001" geometry={nodes.Petal001.geometry} material={materials.PaletteMaterial001} position={[0.016, 2.245, 0.716]} rotation={[0.118, -0.966, 0.038]} />
        <mesh name="Petal002" geometry={nodes.Petal002.geometry} material={materials.PaletteMaterial001} position={[-0.206, 2.232, 0.675]} rotation={[0.273, -1.455, 0.187]} />
        <mesh name="Petal003" geometry={nodes.Petal003.geometry} material={materials.PaletteMaterial001} position={[-0.338, 2.27, 0.574]} rotation={[-3.081, -0.892, 3.107]} />
        <mesh name="Petal004" geometry={nodes.Petal004.geometry} material={materials.PaletteMaterial001} position={[-0.251, 2.303, 0.291]} rotation={[-3.055, -0.025, 3.12]} />
        <mesh name="Petal005" geometry={nodes.Petal005.geometry} material={materials.PaletteMaterial001} position={[-0.212, 2.298, 0.104]} rotation={[-3.045, 0.413, 3.118]} />
        <mesh name="Petal006" geometry={nodes.Petal006.geometry} material={materials.PaletteMaterial001} position={[0.386, 2.392, 0.367]} rotation={[0.073, 0.578, 0.026]} />
        <mesh name="Petal007" geometry={nodes.Petal007.geometry} material={materials.PaletteMaterial001} position={[0.234, 2.336, 0.155]} rotation={[0.055, 0.978, 0.038]} />
        <mesh name="Petal008" geometry={nodes.Petal008.geometry} material={materials.PaletteMaterial001} position={[0.041, 2.338, 0.024]} rotation={[-2.979, 1.293, 3.063]} />
      </mesh>
      <mesh name="PCGlass" geometry={nodes.PCGlass.geometry} material={materials.PaletteMaterial004} position={[-2.436, -3.387, 2.664]}  onPointerOver={(e)=> PlayAnimation({e})} onPointerOut={(e) => PauseAnimation({e})} onClick={(e) => zoomToObject((e.object.parent) ? e.object.parent.position: e.object.position)} >
        <mesh name="Cooler" geometry={nodes.Cooler.geometry} material={materials.PaletteMaterial001} position={[-2.512, 1.664, -3.822]} />
        <mesh name="Cooler001" geometry={nodes.Cooler001.geometry} material={materials.PaletteMaterial001} position={[-3.876, 1.664, -3.822]} />
        <mesh name="Fan" geometry={nodes.Fan.geometry} material={materials.PaletteMaterial001} position={[-5.312, 1.857, -2.374]} rotation={[Math.PI / 2, 0, -Math.PI / 2]}   />
        <mesh name="Fan001" geometry={nodes.Fan001.geometry} material={materials.PaletteMaterial001} position={[4.054, 2.087, -1.964]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.936} />
        <mesh name="Fan002" geometry={nodes.Fan002.geometry} material={materials.PaletteMaterial001} position={[4.038, 0.087, -1.964]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Fan003" geometry={nodes.Fan003.geometry} material={materials.PaletteMaterial001} position={[4.038, -1.913, -1.964]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh name="Part" geometry={nodes.Part.geometry} material={materials.PaletteMaterial001} position={[-3.129, -0.069, -2.516]} />
        <mesh name="Part001" geometry={nodes.Part001.geometry} material={materials.PaletteMaterial001} position={[-1.591, -2.762, -2.49]} />
        <mesh name="Part002" geometry={nodes.Part002.geometry} material={materials.PaletteMaterial001} position={[-3.293, 1.65, -4.027]} />
        <mesh name="PC" geometry={nodes.PC.geometry} material={materials.PaletteMaterial001} position={[0, -0.006, 0]} />
      </mesh>

    </group>
  </group>
  )
}

useGLTF.preload('/portfolio_animated-transformed.glb')
